### ISSUE TITLE
Upgrade kotlin version

### ISSUE THREAD

**Issue by frankenten13** [jeroentrappers/flutter_jailbreak_detection#29]
Error when upgrade flutter 3.3.0, please upgrade
```
* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':flutter_jailbreak_detection' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.31
```

**Comment by cnkygmr** [comment]
Still waiting

**Comment by timnew** [comment]
Same

**Comment by jaggernod** [comment]
The change has already been merged to `master` but not released to https://pub.dev/

I do not recommend it but as a workaround, one can include the dependency via git in `pubspec.yaml`:

```yaml
  flutter_jailbreak_detection:
    git:
      url: git@github.com:jeroentrappers/flutter_jailbreak_detection.git
      ref: 5fe2f04
```
