### ISSUE TITLE
Getting issues while implementing the flutter_jailbreak_detection

### ISSUE THREAD

**Issue by SarthakSharma886** [jeroentrappers/flutter_jailbreak_detection#73]
* What went wrong:
Could not determine the dependencies of task ':flutter_jailbreak_detection:compileDebugKotlin'.
> Unknown Kotlin JVM target: 21

**Comment by rignaneseleo** [comment]
You can use this in your pubspec to load the fixed version:

```
  flutter_jailbreak_detection:
    git:
      url: https://github.com/pdurasie-ecovery/flutter_jailbreak_detection.git
      ref: add-namespace
```
