### ISSUE TITLE
Will this package still function properly, even though it hasn’t been maintained for a while?

### ISSUE THREAD

**Issue by thelordzeus** [jeroentrappers/flutter_jailbreak_detection#75]

**Comment by rignaneseleo** [comment]
You can use this in your pubspec to load the fixed version:

```
  flutter_jailbreak_detection:
    git:
      url: https://github.com/pdurasie-ecovery/flutter_jailbreak_detection.git
      ref: add-namespace
```
